version: '3.8'

services:
  go:
    image: go
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    ports:
      - "8443-8453:8443"
    expose:
      - "8443:8443"
