version: '3.8'

services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8443:8443"
    networks:
      - external_network

networks:
  external_network:
    external:
      name: host
