version: '3.8'

services:
  go:
    image: go
    build:
      context: .
      dockerfile: ./DockerFile
    deploy:
      replicas: 3
    ports:
      - "8443-8445:8443"

  nginx:
    image: nginx
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf

configs:
  nginx_conf:
    file: ./nginx.conf
