version: '3.8'

services:
  go:
    image: go-peynirciler
    build:
      context: .
      dockerfile: ./Dockerfile
    deploy:
      replicas: 1
    ports:
      - "3001:3001"

  #nginx:
   # image: nginx
   # ports:
   #   - "8081:8081"
   # deploy:
   #   replicas: 1
    #configs:
    #  - source: nginx_conf
    #    target: /etc/nginx/nginx.conf

#configs:
#  nginx_conf:
#    file: ./nginx.conf
