version: '3.8'

services:
  go:
    image: yigitsilto/gocommerce1.0.0:latest
   # build:
    #  context: .
     # dockerfile: ./DockerFile
    deploy:
      replicas: 1
    ports:
      - "8443:8443"

 # nginx:
  #  image: nginx
   # ports:
    #  - "8081:8081"
    #deploy:
     # replicas: 1
   # configs:
    #  - source: nginx_conf
     #   target: /etc/nginx/nginx.conf

#configs:
 # nginx_conf:
  #  file: ./nginx.conf
