version: '3.5'

services:
  postgres:
    container_name: goLangEcommerce
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"


volumes:
  postgres-db:
    driver: local